baseURL =  "https://happy-perlman-37c2d7.netlify.com/" 
languageCode = "en-us"
title = "hdwih"
theme = "navigator-hugo"

[[menu.nav]]
        name    = "About"
        url     = "/about"
        weight  = 2
    [[menu.nav]]
        name    = "Service"
        url     = "/services"
        weight  = 3
    [[menu.nav]]
        name    = "Portfolio"
        url     = "/portfolio"
        weight  = 4
    [[menu.nav]]
        name    = "Blog"
        url     = "/blog"
        weight  = 5
    [[menu.nav]]
        name    = "Contact"
        url     = "/contact"
        weight  = 6
    

# Site params

[params]
    home="Home"
    logo="img/Hdwih_Logo.png"

    [params.intro]
    home_banner="img/home.jpeg"
    title="Transformation through awareness"
    summary="We are known to adapting to ambiguous environments. We are  committed to excellence and creating innovative and flexible solutions for our clients.  HDWIH’s principals bring over 45 years of experience with public and private sector."
    btnUrl="/About"
    button="true"
    btnText="Learn More..."

    
    
    # home page front summary section
    [params.intro_sections]
        who_we_are_title="Who We are!"
        who_we_are_summary="HDWIH LLC is a certified Woman-owned Small Business management consulting firm that provides creates and executes strategic human resources management, organizational development, recruitment, executive search and staff augmentation to business, organizations, and overnments globally. We draw on our extensive pool of expert leaders in the United States, Africa, the Caribbean and Latin America.  We are  committed to excellence and creating innovative and flexible solutions for our clients.  Additionally, HDWIH’s principals and staff are multilingual with language capacities in French, Spanish, and Haitian Creole."
        service_title="Service"
        service_summary="nothing"
        professionalism_title="Professionalism"
        professionalism_summary="HDWIH LLC provides high quality management services.  HDWIH LLC. will work with your organization every step of the way to make sure you received the services you need. HDWIH LLC. is client-oriented, and we maintain strict confidentiality"
        what_we_do_title="What we do!"
        what_we_do_summary="We are dedicated to understanding your business, to being flexible and holistic in our approach by responding to our customer’s changing needs so that we can develop the value we bring to each relationship. We are known to adapting to ambiguous environments."
    
     
     # Contact Section
    [params.contact]
        enable  = true
        topTitle= "Get in touch with us"
        title   = "Contact Us."
        subtitle= "{{insert some text here}}"
        address = "4242 East- West Highway - Suite 909 - Chevy Chase, Maryland 20815, United States"
        phone   = "(240) 463 1555"
        fax     = "+61 3827 3590"
        facebook= "https://www.facebook.com/HDWIHLLC"
        #twitter = "https://twitter.com/"
        #linkedin= "https://www.linkedin.com/"
        #dribbble= "https://dribbble.com/"
        #instagram= "https://www.instagram.com/"
        #mapLatitude = "51.507351"
        #mapLongitude= "-0.127758"
        #mapMarker   = "images/marker.png"