backend:
  name: git-gateway
  branch: master 
  publish_mode: editorial_workflow
  
media_folder: "static/img"

collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'About Page'
        name: 'about'
        file: 'data/about.yml'
        fields:
          - { label: Enable, name: enable, widget: boolean }
          - label: Item
            name: item
            widget: list
            fields:
              - { label: PositionRight, name: positionRight, widget: boolean }
              - { label: Image, name: image, widget: image }
              - { label: Title, name: title, widget: string}
              - { label: Description, name: description, widget: markdown }
      
  

