backend:
  name: git-gateway
  branch: master 
  
publish_mode: editorial_workflow
media_folder: "static/img"

collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'About Page'
        name: 'about'
        file: 'data/about.yml'
        fields:
          - { label: Enable, name: enable, widget: boolean }
          - label: About Section
            name: item
            widget: list
            fields:
              - { label: PositionRight, name: positionright, widget: boolean }
              - { label: Image, name: image, widget: image }
              - { label: Title, name: title, widget: string } 
              - { label: Description, name: description, widget: markdown }
  - label: 'Sections'
    name : 'sections'
    files:
      - label: 'Clients section'
        name: 'clients'
        file: 'data/clients.yml'
        fields:
          - { label: Enable, name: enable, widget: boolean }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - label: Service List
            name: servicelist
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
          - label: 'Client Logos'
            name: 'clientlogo'
            widget: list
            fields:
              - { label: Image, name: image, widget: image }
      - label: 'NAICS section'
        name: 'naics'
        file: 'data/naics.yml'
        fields:
          - { label: Enable, name: enable, widget: boolean }
          - { label: Title, name: title, widget: string }
          - { label: Top Title, name: topTitle, widget: string }
          - label: Codes
            name: codes
            widget: list
            fields:
              - label: code
                name: code
                widget: object
                fields:
                  - { label: Value, name: value, widget: string }
                  - { label: Description, name: description, widget: markdown }
      - label: 'CEO bio section'
        name: 'ceobio'
        file: 'data/philosophy.yml'
        fields:
          - { label: Enable, name: enable, widget: boolean }
          - { label: Title, name: title, widget: string }
          - { label: Top Title, name: topTitle, widget: string }
          - { label: BioTitle, name: media_head, widget: string }
          - { label: BioBody, name: media_body, widget: markdown }
          - { label: Image, name: image, widget: image }
          - label: History
            name: history
            widget: hidden
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Heading, name: heading, widget: string }
              - { label: Content, name: content, widget: markdown }
              - { label: Image, name: image, widget: image }
          - label: Mission
            name: mission
            widget: hidden
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Heading, name: heading, widget: string }
              - { label: Content, name: content, widget: markdown }
              - { label: Image, name: image, widget: image }
          
