backend:
  name: git-gateway
  branch: master 
  
publish_mode: editorial_workflow
media_folder: "static/img"

collections:
  - label: "Blog"
    name: "blog"
    folder: "content/blog"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
     # - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Home Page'
        name: 'home'
        file: 'data/home.yml'
        fields:
            - { label: Home Top Banner, name: home_banner, widget: image }
            - { label: Home Top Banner Title/Slogan, name: title, widget: string }
            - { label: Home Top Banner Summary, name: summary, widget: text} 
            - { label: Home Top Banner Button Link, name: btnUrl, widget: string }
            - { label: Home Top Banner Button Enabled, name: button, widget: boolean }
            - { label: Home Top Banner Button Text, name: btnText, widget: string }
            - { label: Certification Image, name: certification_img, widget: image }
            - { label: Home Page Who We Are Title , name: who_we_are_title, widget: string }
            - { label: Home Page Who We Are Summary Text, name: who_we_are_summary, widget: text}
            - { label: Home Page Service Section Title, name: service_title, widget: string }
            - { label: Home Page Service Section Summary, name: service_summary, widget: text }
            - { label: Home Page Profesionalism Section Title, name: professionalism_title, widget: string }
            - { label: Home Page Service Section Summary, name: professionalism_summary, widget: text}
            - { label: Home Page What We Do Section Title, name: what_we_do_title, widget: string }
            - { label: Home Page What We Do Section Summary , name: what_we_do_summary, widget: markdown }
      - label: 'Contact Page'
        name: 'contact'
        file: 'data/contact.yml'
        fields:
          - { label: Enable, name: enable, widget: boolean }
          - { label: Top Title, name: topTitle, widget: string }
          - { label: Title,  name: title, widget: string}
          - { label: Email Info, name: subtitle, widget: text } 
          - { label: Address, name: address, widget: markdown }
          - { label: Phone, name: phone, widget: text }
          - { label: Fax, name: fax, widget: text }
  - label: 'Sections'
    name : 'sections'
    files:
      - label : 'Home Page Sections'
        name: 'Home Sections'
        file: 'data/about.yml'
        widget: list
        fields:
              - { label: PositionRight, name: positionright, widget: boolean }
              - { label: Image, name: image, widget: image }
              - { label: Title, name: title, widget: string } 
              - { label: Description, name: description, widget: markdown }
      - label: 'Clients section'
        name: 'clients'
        file: 'data/clients.yml'
        fields:
          - { label: Enable, name: enable, widget: boolean }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - label: Service List
            name: servicelist
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
          - label: 'Client Logos'
            name: 'clientlogo'
            widget: list
            fields:
              - { label: Image, name: image, widget: image }
      - label: 'NAICS section'
        name: 'naics'
        file: 'data/naics.yml'
        fields:
          - { label: Enable, name: enable, widget: boolean }
          - { label: Title, name: title, widget: string }
          - { label: Top Title, name: topTitle, widget: string }
          - label: Codes
            name: codes
            widget: list
            fields:
              - label: code
                name: code
                widget: object
                fields:
                  - { label: Value, name: value, widget: string }
                  - { label: Description, name: description, widget: markdown }
      - label: 'CEO bio section'
        name: 'ceobio'
        file: 'data/philosophy.yml'
        fields:
          - { label: Enable, name: enable, widget: boolean }
          - { label: Title, name: title, widget: string }
          - { label: Top Title, name: topTitle, widget: string }
          - { label: BioTitle, name: media_head, widget: string }
          - { label: BioBody, name: media_body, widget: markdown }
          - { label: Image, name: image, widget: image }
          - label: History
            name: history
            widget: hidden
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Heading, name: heading, widget: string }
              - { label: Content, name: content, widget: markdown }
              - { label: Image, name: image, widget: image }
          - label: Mission
            name: mission
            widget: hidden
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Heading, name: heading, widget: string }
              - { label: Content, name: content, widget: markdown }
              - { label: Image, name: image, widget: image }
          
